platform :ios, '12.0'
use_frameworks!

workspace 'Sample'
project 'Sample'

target 'Sample' do
    pod 'NI18n', :path => './../'
end

target 'SampleTests' do
    pod 'NI18n/TestHelpers', :path => './../', :testspecs => ['Tests']
end
